//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestion
    {
        public int SettingID { get; set; }
        public int QuestionID { get; set; }
    
        public virtual ExamSetting ExamSetting { get; set; }
    }
}
