//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roster
    {
        public int UserID { get; set; }
        public int BatchID { get; set; }
        public int Status { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual StatusType StatusType { get; set; }
        public virtual User User { get; set; }
    }
}
