//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS1701.USL.UBEAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamAssessment
    {
        public int ExamAssessmentID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<int> SettingsID { get; set; }
        public Nullable<System.TimeSpan> TimeRemaining { get; set; }
        public Nullable<bool> IsExamComplete { get; set; }
        public Nullable<decimal> Score { get; set; }
    
        public virtual ExamSetting ExamSetting { get; set; }
        public virtual User User { get; set; }
    }
}
