//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS1701.USL.UBEAPI.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionOrder
    {
        public int QuestionNumber { get; set; }
        public string QuestionID { get; set; }
        public int QuestionOrderID { get; set; }
        public int ExamAssessmentFK { get; set; }
    
        public virtual ExamAssessment ExamAssessment { get; set; }
        public virtual QuestionAnswer QuestionAnswer { get; set; }
    }
}
